[graph]
all-features        = false
no-default-features = false
targets             = []

[output]
feature-depth = 1

[licenses]
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "MIT",
  "MPL-2.0",
  "NCSA",
  "OpenSSL",
  "Unicode-3.0",
]
exceptions = []

[licenses.private]
ignore     = true
registries = []
